# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{filterrific}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jo Hund"]
  s.date = %q{2010-08-01}
  s.description = %q{
      The Rails User Interface solution for filtering your ActiveRecord lists:

      * Built from the ground up for Rails3
      * Build filter forms with ease
      * Filter ActiveRecord lists using AR scopes
      * Shuttle filter parameters from view to controller to model in a RESTful way
      * Auto-generate scopes for AR associations (Planned)
      * Form builder for filter UI forms (Planned)
    }
  s.email = %q{jhund@clearcove.ca}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.md",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/Overview diagram.graffle/QuickLook/Preview.pdf",
     "doc/Overview diagram.graffle/QuickLook/Thumbnail.tiff",
     "doc/Overview diagram.graffle/data.plist",
     "doc/Overview diagram.graffle/image1.tiff",
     "doc/documentation.md",
     "doc/ideas.txt",
     "doc/todo.md",
     "doc/workflow.md",
     "filterrific.gemspec",
     "lib/filterrific.rb",
     "lib/filterrific/model_mixin.rb",
     "lib/filterrific/param_set.rb",
     "lib/filterrific/railtie.rb",
     "lib/filterrific/view_helpers.rb",
     "test/helper.rb",
     "test/test_filterrific.rb"
  ]
  s.homepage = %q{http://github.com/jhund/filterrific}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{The Rails User Interface solution for filtering your ActiveRecord lists.}
  s.test_files = [
    "test/helper.rb",
     "test/test_filterrific.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

